#include <iostream>
using namespace std;

//konieczne aby na koñcu tekstu daæ dwa odstêpy, po nich metoda rozpozna, ¿e koniec tekstu


//korytarze
string h1 = "Pod¹¿asz d³ugim i zimnym korytarzem. Sciany pokryte s¹ mchem a z sufitu zwisaj¹ liany. Pod stopami czujesz ziemiê a powietrze wype³nuie niespecjalnie przyjemny zapach.  ";
string h2 = "Pod¹¿asz krêtym korytarzem Pokrytym rozgrzanymi od ognia kamieniami. Tunel jest krêty a w niektórych miejscach ze szczelin w œcianach ulatuje para. Temperatura jest wysoka a w powietrzu roznosi siê zapach siarki. Grunt pod nogami jest niepewny, wiêc przyspieszasz kroku.  ";
string h3 = "Korytarz, którym idziesz jest wyj¹tkowo w¹ski, jednak pod³oga wy³o¿ona jest kamiennymi ceg³ami. Œciany s¹ zimne a z sufitu miejscami kapi¹ krople wody.  ";
string h4 = "Korytarz prowadzi schodami w dó³. S¹ one strome i niebezpieczne a kamienne œciany s¹ zimne niczym lód. Prawie potykasz siê o jeden ze stopni, jednak w porê ³apiesz równowagê i schodzisz dalej.  ";
string h5 = "Korytarz, którym pod¹¿asz jest d³ugi i krêty. Œciany przypominaj¹ kamienne mury, sufit jest wysoko nad Twoj¹ g³ow¹. Niekiedy po bokach dostrzegasz zamkniête drzwi z ciemnego drewna, jednak próby ich otwarcia koñcz¹ siê niepowodzeniem. Nie zastanawiaj¹c siê d³ugo, pod¹¿asz dalej.  ";

string gonext = "Docierasz do rozwidlenia korytarza. Mo¿esz pod¹¿yæ tunelem na wschód, zachód lub na pó³noc  ";

//sala z przeciwnikiem
string s1 = "Wkraczasz do zimnej i ponurej sali. Z sufitu zwisa podniszczony ¿yrandol na którym pali siê kilka œwiec. Wzd³ó¿ jednej ze œcian stoj¹ równo u³o¿one trumny. W jednej z nich dostrzegasz niewielk¹ stertê z³otych monet!. Niestety, nie s¹ one niepilnowane. Dooko³a skarbu przechadza siê uzbrojony w d³ugi miecz ¿ywy szkielet!. upiorny stra¿nik wodzi wzrokiem po pod³odze a jego broñ wydaje siê ostra i groŸna...  ";
string s2 = "Docierasz do sporych rozmiarów sal. Œciany s¹ zabite deskami, w niektórych miejscach ze œcian zwisaj¹ zwierzêce skóry. Na œrodku sali dostrzegasz niewielk¹ szkató³kê. Bez w¹tpienia skrywa ona niema³y skarb. Jednak kiedy robisz krok w stronê szkató³ki, zzajednej ze skór wy³ania siê wielki, paskudny, zielony ogr! Trzyma on w d³oniach maczugê	obit¹ kolcami. Stra¿nik rozgl¹da siê po sali otêpia³ym wzrokiem i mruczy coœ pod nosem.  ";
string s3 = "Wkraczasz do sali niemal¿e ca³kowicie poroœniêtej mchem i latoroœlami. Gdyby nie œwiadomoœæ, ¿e jest siê w podziemiu to mo¿na by odnieœæ wra¿enie, ¿e jest siê na leœnej polanie. Na œrodku owej polany dostrzegasz niewielk¹ fontannê oraz z³oty po³ysk nad ni¹. Niew¹tpliwie jest ona wype³niona drogocennymi monetami. Jednak nie jest ona niestrze¿ona. Dooko³a fontanny kr¹¿y blada niczym mg³a zjawa, jej szare szaty powiewaj¹ dooko³a a twarz wydaje siê smutna i nieszczêœliwa. Zdobycie skarnu mo¿e okazaæ siê trudniejsze ni¿ pocz¹tkowo siê zdawa³o.  ";
string s4 = "Sala w której siê znajdujesz wygl¹da niczym laboratorium. przy œcianach ustawione s¹ rega³y z ksi¹¿kami oraz wszelakie przyrz¹dy alchemiczne. Kamienna posadzka urbudzona jest licznymi plamami po kwasie a w powietrzu unosi siê ciê¿ki do zidentyfikowania zapach. Na koñcu sali dostrzegasz elegancki stolik na którym znajduj¹ siê z³ote monety! Istnt skarb, prawdziwa nagroda. Niestety, po pomieszczeniu krêci siê ponury mê¿czyzna w czarnych szatach z kapturem. W d³oni trzyma magiczny kostur, niew¹tpliwie masz do czynienia z czarnoksiê¿nikiem! Nie jest to ³atwy przeciwnik, jednak skarb le¿¹cy na stole kusi...  ";
string s5 = "Sala do której wkraczsz przypomina bardziej kana³ œciekowy ni¿ komnatê. Metalowe œciany s¹ pokryte œladami rdzy a z sufitu kapi¹ krople brudnej wody. W roku sali dostrzegasz sporych rozmiarów wy³om z wyrwan¹ krat¹, dooko³a unosi siê smród zepsutego jedzenia. W tej paskudnej sali, jedyne co mo¿na nazwaæ '³adnym' to niema³a sterta z³otych monet, która le¿y na niewielkim piedestale. Kiedy jednak wykonujesz krok do przodu, z wy³omu dobiega przera¿aj¹cy ryk. Z ciemnoœci wy³ania siê straszliwa, olbrzymich rozmiarów ropucha. Wodzi œlepo wzrokiem po sali, jednak nie widzi ciê wyraŸnie. Widaæ d³ugie lata w podziemiu uszkodzi³y powa¿nie wzrok besti.  ";

//sala ze skarbem
string t1 = "Odwa¿nym krokiem wkraczasz do sali. Jest ona wyj¹tkowo niewielka, jednak przypomina ca³kiem zadban¹ komnatê zamkow¹. Na kamiennych œcianach wisz¹ arrasy, z sufitu zwisa bogaty ¿yrandol. Na samym œrodku sali znajduje siê dêbowa ³awa. Poza licznymi pergaminami oraz nieczytelnymi apiskami, dostrzegasz niewielk¹ szkató³kê. Byæ mo¿e zawiera ona coœ cennego.  ";
string t2 = "Wkraczasz do olbrzymich rozmiarów sali. Przypomina ona opuszczony szyb kopalniany. Na œcianach wisz¹ kilowy oraz narzêdzia górnicze. Szyb prowadzi wg³¹b sali i staje siê coraz wê¿szy. Na samym koñcu dostrzegasz wyjœcie, jednak zaraz obok niego zauwa¿asz sporych rozmiarów skrzynkê. Nie wygl¹da to na pierwszy lepszy kontener na wegiel, obicia skrzyni s¹ eleganckie i zdobione.  ";
string t3 = "Wchodzisz do sali niemal¿e ca³kowicie spowitej w ciemnoœæ. Twoja pochodnia wydaje siê gasn¹æ a w ca³ej sali nie dostrzegasz ¿adnego Ÿród³a œwiat³a. Nieewnym krokiem ruszasz przed siebie. Po kilku krokach dostrzegasz zarys drzwi, które prawdopodobnie pozwol¹ Ci opóœciæ to podejrzane miejsce. Ruszaj¹c w stronê drzwi, nagle potykasz siê o jakiœ przedmiot. Po dok³adniejszym wymacaniu oraz zbli¿eniu pochodni ustalasz, ¿e jest to zamkniêta skrzynka. Byæ mo¿e przed opuszczeniem sali warto zobaczyæ czy nie skrywa jakiœ skarbów?  ";
string t4 = "¯wawym krokiem wkraczasz do kolejnej komnaty. Ju¿ na wejœciu przeszywa Ciê okrutne wrêcz zimno. Sala w której siê znajdujesz przypomina lodowy grobowiec, œciany zbudowane s¹ z pokrytej gêst¹ warstw¹ lodu kamiennej ceg³y a pod³oga us³ana jest szronem i œniegiem. Œwiat³o w komnacie rzucaj¹ ustawione w rogach sali kot³y p³on¹ce ogniem o niebieskiej barwie. Nie czuæ jednak ¿adnego ciep³a od strony owych p³omieni. Na œrodku sali stoi kamienny sarkofag... Jego wieko jest otwarte a w œrodku wype³niony jest lodowat¹ wod¹. Na dnie dostrzegasz jednak niewielk¹ szkató³kê. Kto wie jake skarby ona skrywa.  ";
string t5 = "Jeszcze przed przekroczeniem progu sali uderza w Ciebie olbrzymia fala ciep³a. Odruchowo zamykasz powieki, jednak kiedy je otwierasz, Twoim oczom ukazuje siê olbrzymich rozmiarów pomieszczenie. Nie jest to komnata, wygl¹da bardziej na wulkaniczn¹ jaskienie. Posadzka pokryta jesy kamieniami wuklanicznymi a po œcianach sp³ywaj¹ strózki lawy. Poprzez rozpadlinê, prowadzi niewielki kamienny most. Nie jest on specjalnie solidny, jednak powinien wytrzymaæ. Powolnym krokiem przemierzasz salê staraj¹æ siê nie patrzeæ w liczne wyrwy zalane law¹. Dostrzegasz wyjœcie! Na koñcu mostu, poza drzwiami znajduje siê jednak kamienny o³tarzyk. Poza le¿¹cymi na nim zwojami o niemo¿liwej dla Ciebie do odczytania treœci, znajdujesz le¿¹c¹ spokojnie skrzynkê. Zapewne skrywa w sobie drogocenne skarby.  ";

//sala z wydarzeniem
string e1 = "Sala do któej wkraczasz przypomina na pierwszy rzut oka niewielk¹ polankê. Spwoija j¹ tajemnicza aura a powietrze wype³nione jest œwie¿ym zapachem drzew. Mimo wszystko, sala jest niewielka i przypomina bardziej podziemn¹ grotê ani¿eli komantê. Poœród niewyskokich krzaków, dostrzegasz œrednich rozmiarów sadzawkê. Unosi siê nad ni¹ kolorowa mgie³ka a sama woda jest krystalicznie czysta. Jednak nie jesteœ w stanie ustaliæ czy ciecz wype³niaj¹ca sadzawkê rzeczywiœcie jest wod¹. Kiedyœ w Twoje rêce wpad³a tajemnicza ksi¹¿ka opowiadaj¹ca o zaczarowanych podziemnych Ÿród³ach wody o nieopisanych w³aœcieoœciach. Byæ mo¿e w³aœnie natrafiasz na jedno z takich.  ";
string e2 = "Wkraczasz do kolejnej sali. Stajesz na twardej, kamiennej posadzce i rozgl¹dasz siê dooko³a. Komnata bez w¹tpienia jest kuŸni¹, na scianasz dostrzegasz drogo wykonane miecze, topory oraz wszelkiego rodzaju rysztunek bojowy. Na œrodku sali znajduje siê olbrzymie kowad³o oraz sporych rozmiarów piec hutniczy. Przy nim dostrzegasz niewysokiego, krêpego krasnoluda. Znad jego g³owy wydobywaj¹ siê k³êby dymu fajkowego. Stoi on ty³em do Ciebie i prawdopodobnie nie zorientowa³ siê o tym, ¿e ktoœ wkroczy³ do jego kuŸni. Nieznajomy mo¿e nie jest wrogiem i byæ mo¿e warto zamieniæ z nim kilka s³ów.  ";
string e3 = "Wchodzisz do tajemniczej i ponurej sali. Poza drzwiamy wyjœciowymi nie znajduje siê tam absolutnie nic. Z rozczarowaniem ruszasz w stronê wyjœcia, jednak w pewnym momencie dostrzegasz, ¿e w rogu pomieszczenia stoi tajemnicza postaæ odziana w czarne szaty. Stoi do Ciebie przodem, jednak jej twarz skryta jest pod kapturem. Nieznajomy nie rusza siê oraz nic nie mówi. Dooko³a niego roztacza siê atmosfera strachu i tajemniczoœci. Mimo, ¿e nie dostrzegasz twarzy nieznajomego to czujesz, ¿e wzrok postaci skierowany jest na Ciebie...  ";
string e4 = "Powolnym ruchem otwierasz drzwi i wkrazasz do dobrze oœwietlonej sali. Œciany s¹ zrobione z drewna, dostrzegasz na nich liczne mechanizmy oraz ko³a zêbate. Po drugiej stronie widaæ drzwi wyjœciowe, jednak dzieli Ciê od nich straszliwy mechanizm. Z pod³ogi sekwencyjnie wyskakuj¹ kolce oraz ¿elazne prêty, co kilka chwil w powietrzu przelatuj¹ ostrza a z sufitu zwisaj¹ liczne ³ancuchy. Przed Tob¹ rozpoœciera siê olbrzymia i skomplikowana pu³apka, której pokonanie jest niezbêdne. W pewnym momencie, pu³apka siê wy³¹cza. Wszystkie mechanizmy staj¹ a przejœcie stoi naprzeciwko Ciebie. Jednak nie wiadomo czy w momencie wst¹pienia na pu³apkê nie uruchomi siê ona ponownie. Trzeba ustaliæ sprytny plan, który pozwoli Ci pokonaæ t¹ œmierteln¹ przeszkodê.  ";
string e5 = "Sala do której wkraczasz zdecydowanie ró¿ni sie od poprzednich. Panuje w niej atmosfera niepokoju i grozy. Œciany wykonane s¹ z czarnego kamienia, pod³oga z szarych kamieni a z sufitu spadaj¹ krople wody. Poza wyjœciem, w sali znajduje siê tylko jeden element. Jest to sporych rozmiarów totem stoj¹cy idealnie na samym œrodku sali. Drzemie w nim nieopisana moc, si³y chaosu, które zosta³y zamkniête w totemie czekaj¹ na kogoœ kto je uwolni. Kiedyœ w Twoje d³onie wpad³a ksi¹¿ka opowiadaj¹ca o takich totemach, ponoæ osoba, która je dotknie, zostanie pob³ogos³awiona tajemniczymi mocami chaosu, które, zale¿nie od kaprysu, zeœl¹ na podróznika wszelakie b³ogos³awieñstwa, lub kl¹twy. Zimny i mroczny totem sykonany jest z kryszta³u, który rzuca dooko³a jasrawy blask...  ";

//sala specjalna
string sp1 = "Sala z gór¹ z³ota  ";
string sp2 = "gra w koœci  ";
string sp3 = "puszka pandory  ";
string sp4 = "'stra¿nik  ";